//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDBEF.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lesuser13Entities : DbContext
    {

        private static lesuser13Entities _context;
        public static lesuser13Entities GetContext()
        {
            if (_context == null)
                _context = new lesuser13Entities();
            return _context;
        }
        public lesuser13Entities()
            : base("name=lesuser13Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Postavchiki> Postavchiki { get; set; }
        public virtual DbSet<Tovarbl> Tovarbl { get; set; }
    }
}
