//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDBEF.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovarbl
    {
        public int ID { get; set; }
        public string Название_товара { get; set; }
        public Nullable<int> Колво_на_складе { get; set; }
        public string Стоимость_ед_товара { get; set; }
        public string Описание_товара { get; set; }
        public string Единица_измерения { get; set; }
        public Nullable<int> ID_Поставщика { get; set; }
    
        public virtual Postavchiki Postavchiki { get; set; }
    }
}
