//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDBEF.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uchebnayaDrugovaEntities : DbContext
    {
        private static uchebnayaDrugovaEntities _context;
        public static uchebnayaDrugovaEntities GetContext()
        {
            if (_context == null)
                _context = new uchebnayaDrugovaEntities();
            return _context;
        }
        public uchebnayaDrugovaEntities()
            : base("name=uchebnayaDrugovaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pabotbl> Pabotbl { get; set; }
        public virtual DbSet<Porychenia> Porychenia { get; set; }
    }
}
