//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDBEF.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pabotbl
    {
        public int ID_shifr { get; set; }
        public string Nazvanie { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> Data_vbIdachi { get; set; }
        public Nullable<System.DateTime> Data_okonchania { get; set; }
        public Nullable<int> ID_nomer { get; set; }
        public string Images { get; set; }
    
        public virtual Porychenia Porychenia { get; set; }
    }
}
