//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDBEF.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Porychenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Porychenia()
        {
            this.Pabotbl = new HashSet<Pabotbl>();
        }
    
        public int ID_nomer { get; set; }
        public string Doljnostb { get; set; }
        public Nullable<int> Trudoemkostb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pabotbl> Pabotbl { get; set; }
    }
}
